language: node_js
node_js:
  - 14

after_success:
  - npm install -g rollup
  - npm install
  - npm run cypress:ci
  - npm run build-storybook

notifications:
  email:
    recipients:
      - saurabhnemade@yandex.com
    on_success: always
    on_failure: always
